### ISSUE TITLE
Any way to run Vale only on changed files in a PR (github workflow)?

### ISSUE THREAD

**Issue by Kayx23** [errata-ai/vale#596]
Hello! I'd like to only run Vale on changed files in a PR (based on all commits in the PR). My github workflow config file is as follows:

```
name: reviewdog
on: [pull_request]

jobs:
  vale-linter:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get changed files in the PR
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}:refs/remotes/origin/base
          git diff --name-only --diff-filter=d $(git merge-base HEAD origin/base)..HEAD > changed_files_in_PR.txt
      - uses: errata-ai/vale-action@reviewdog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: $(cat changed_files_in_PR.txt)
          reporter: github-check
          fail_on_error: true
```

Getting the warning in the stout: `Warning: User-specified path ($(cat changed_files_in_PR.txt)) is invalid; falling back to 'all'.`

Any help would be highly appreciated!

**Comment by cymruu** [comment]
I think what's happening is that GitHub is treating the input files as a string literal, which means the command isn't being executed. To fix this, you need to actually execute `cat` on that file and save the result into a variable 

```
- name: Set variables
  run: |
    CHANGED_FILES=$(cat changed_files_in_PR.txt)
    echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
```
and then use created environmental variable in last step

```
 - uses: errata-ai/vale-action@reviewdog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: ${{env.CHANGED_FILES}}
          reporter: github-check
          fail_on_error: true
```
